// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class Admin
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public string UserName { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public int? Auth { get; set; }

    public string WorkPosition { get; set; }

    public string StaffNo { get; set; }

    public int DepartmentId { get; set; }

    public string AdminToken { get; set; }

    public string AvatarUrl { get; set; }

    public bool? Status { get; set; }
}