// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class AdminNotificationReadLogs
{
    public int Id { get; set; }

    public int AdminNotificationId { get; set; }

    public int AdminId { get; set; }

    public int CompanyId { get; set; }

    public DateTime ReadDate { get; set; }
}