// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class AmendCheckRecord
{
    public int StaffId { get; set; }

    public int CompanyId { get; set; }

    public DateTime CheckDate { get; set; }

    public DateTime CheckTime { get; set; }

    public int CheckType { get; set; }

    public string Reason { get; set; }

    public int IsValidate { get; set; }

    public string Inspector { get; set; }

    public DateTime? ValidateDate { get; set; }

    public int Id { get; set; }

    public string Applicant { get; set; }

    public DateTime ApplicationDate { get; set; }
}