// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class Application
{
    /// <summary>
    /// 編號
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    public string ApId { get; set; }

    /// <summary>
    /// 密碼
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    public string ApName { get; set; }

    /// <summary>
    /// 狀態
    /// </summary>
    public bool Status { get; set; }

    /// <summary>
    /// 權杖
    /// </summary>
    public string Token { get; set; }

    /// <summary>
    /// 權杖效期
    /// </summary>
    public DateTime? Expire { get; set; }

    /// <summary>
    /// 不驗證 LINE UserId
    /// </summary>
    public bool SkipLineUserId { get; set; }
}