// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class CheckRecords
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int StaffId { get; set; }

    public DateTime? CheckInTime { get; set; }

    public DateTime? CheckOutTime { get; set; }

    public string CheckInMemo { get; set; }

    public string CheckOutMemo { get; set; }

    public int? IsCheckInOutLocation { get; set; }

    public int? IsCheckOutOutLocation { get; set; }

    public int? IsCheckInLate { get; set; }

    public int? CheckInLateTimes { get; set; }

    public int? CheckOutEarlyTimes { get; set; }

    public int? IsCheckOutEarly { get; set; }
}