// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class Company
{
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public double? CapitalAmount { get; set; }

    public string Address { get; set; }

    public string Coordinate { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public int? ContractType { get; set; }
}