// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class ContractTypeList
{
    public int Id { get; set; }

    public int ContractType { get; set; }

    public int AdminLimit { get; set; }

    public int StaffLimit { get; set; }
}