// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class Department
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int CompanyRuleId { get; set; }

    public string DepartmentName { get; set; }
}