// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class IncomeLogs
{
    public int Id { get; set; }

    public int StaffId { get; set; }

    public int CompanyId { get; set; }

    public DateTime IssueDate { get; set; }

    public int BasicSalary { get; set; }

    public int? FullCheckInMoney { get; set; }

    public int? Bonus { get; set; }

    public int? SickHours { get; set; }

    public int? ThingHours { get; set; }

    public int? MenstruationHours { get; set; }

    public int? ChildbirthHours { get; set; }

    public int? MiscarriageHours { get; set; }

    public int? TackeCareBabyHours { get; set; }

    public int? IncomeTax { get; set; }

    public int HealthInsurance { get; set; }

    public int WorkerInsurance { get; set; }

    public int EmployeeRetirement { get; set; }

    public int SupplementaryPremium { get; set; }

    public int HealthInsuranceFromCompany { get; set; }

    public int WorkerInsuranceFromCompany { get; set; }

    public int EmployeeRetirementFromCompany { get; set; }

    public int AdvanceFundFromCompany { get; set; }

    public int IsMakeSure { get; set; }

    public int StaffIncomeAmount { get; set; }

    public int StaffActualIncomeAmount { get; set; }

    public int StaffDeductionAmount { get; set; }

    public int CompanyCostAmount { get; set; }

    public int OverTimeHours { get; set; }
}