// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class MeetLog
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int? StaffId { get; set; }

    public int? DepartmentId { get; set; }

    public string Title { get; set; }

    public string Detail { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan? EndTime { get; set; }

    public string Creator { get; set; }

    public DateTime? CreateDate { get; set; }
}