// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class NotificationLogs
{
    public int Id { get; set; }

    public int StaffId { get; set; }

    public int CompanyId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Type { get; set; }

    public bool IsUnRead { get; set; }

    public DateTime CreateDate { get; set; }

    public string Creator { get; set; }

    public int DepartmentId { get; set; }

    public string ReadStaffIds { get; set; }
}