// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class OverTimeLog
{
    public int Id { get; set; }

    public DateTime OvertimeDate { get; set; }

    public int OverHours { get; set; }

    public int CompanyId { get; set; }

    public int StaffId { get; set; }

    public int IsValidate { get; set; }

    public string Inspector { get; set; }

    public int? InspectorId { get; set; }

    public DateTime? ValidateDate { get; set; }

    public string Reason { get; set; }
}