// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class PersonalDetail
{
    public int Id { get; set; }

    public int StaffId { get; set; }

    public int CompanyId { get; set; }

    public string Name { get; set; }

    public string EnglishName { get; set; }

    public DateTime BirthDay { get; set; }

    public string Gender { get; set; }

    public int IsMarried { get; set; }

    public int HasLicense { get; set; }

    public double Height { get; set; }

    public int Weight { get; set; }

    public string IdentityNo { get; set; }

    public int? HasCrimeRecord { get; set; }

    public string Memo { get; set; }
}