// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Human.Repository.EF;

public partial class UpdateStaffInfoLogs
{
    public int Id { get; set; }

    public DateTime UpdateTime { get; set; }

    public int Finished { get; set; }

    public string ErrorMessage { get; set; }
}